image: snake-game-game:latest
imagePullPolicy: Never
replicas: 1
port: 50055
command: ["/root/bin/game_server"]
mongodbUri: "mongodb://admin:password@mongodb:27017"

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
