apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
- path: lobby/values.yaml
  target:
    kind: Deployment
    name: lobby
- path: matching/values.yaml
  target:
    kind: Deployment
    name: matching
- path: room/values.yaml
  target:
    kind: Deployment
    name: room
- path: leaderboard/values.yaml
  target:
    kind: Deployment
    name: leaderboard
- path: game/values.yaml
  target:
    kind: Deployment
    name: game
- path: friends/values.yaml
  target:
    kind: Deployment
    name: friends
- path: gateway/values.yaml
  target:
    kind: Deployment
    name: gateway