apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
      - name: gateway
        env:
        - name: LOG_LEVEL
          value: "warn"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby
spec:
  template:
    spec:
      containers:
      - name: lobby
        env:
        - name: LOG_LEVEL
          value: "warn"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching
spec:
  template:
    spec:
      containers:
      - name: matching
        env:
        - name: LOG_LEVEL
          value: "warn"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room
spec:
  template:
    spec:
      containers:
      - name: room
        env:
        - name: LOG_LEVEL
          value: "warn"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard
spec:
  template:
    spec:
      containers:
      - name: leaderboard
        env:
        - name: LOG_LEVEL
          value: "warn"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  template:
    spec:
      containers:
      - name: game
        env:
        - name: LOG_LEVEL
          value: "warn"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: friends
spec:
  template:
    spec:
      containers:
      - name: friends
        env:
        - name: LOG_LEVEL
          value: "warn"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"