image: snake-game-room:latest
imagePullPolicy: Never
replicas: 1
port: 50053
command: ["/root/bin/room_server"]
mongodbUri: "mongodb://admin:password@mongodb:27017"

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
