image: snake-game-friends:latest
imagePullPolicy: Never
replicas: 1
port: 50056
command: ["/root/bin/friends_server"]
mongodbUri: "mongodb://admin:password@mongodb:27017"

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
