apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snake-game-debug
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:wdazhi97/deployment.git
    targetRevision: HEAD
    path: env/debug/overlay

  destination:
    server: https://kubernetes.default.svc
    namespace: snake-game-debug

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
