apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- mongodb/deployment.yaml
- lobby/deployment.yaml
- matching/deployment.yaml
- room/deployment.yaml
- leaderboard/deployment.yaml
- game/deployment.yaml
- friends/deployment.yaml
- gateway/deployment.yaml
- frontend/deployment.yaml
- otel/deployment.yaml

namespace: snake-game-debug

labels:
- pairs:
    environment: debug
  includeSelectors: false
